language: node_js
node_js:
- '4.0'
- '9.0'
after_script: bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: Kt8bUA2b9u5Iia6Fq3z4FGLIdXR3YRsojLrmWnk0VAUZNsA0oBm/9/K5ehbMrwhhyn+NMsYQQ5tiDCHWk9n45Eb8TVXPJZXCgs5kh64IPp4pqoKITYcArg325GcZfjG/tj7X+cuWVaxVDG5MA7h78DacC9jyV0nK6dIlCcWM3/vlwGJPyvUo53eFPLRudjSmHBLefsr10UBZ4xr7dcklQJ4UJXAVjVX6+3kUH671idH++Ey2/nns/57BYIdXMIt334JSNm0noT5cOG+lzP6Tk1aSMCtSryNpCi6fw/49duelhQNnEqXa7gDy2DIL8eB7wwtZr3rprw319kPirTpxaLEPulC2ZYCJjaFuw3IquTljDBwEc4FfFwOp+Q1cn/OoHAvnkstGTNhFE+8YAX79RF9nNt1XFYDJ8g8VfX7ndYiDuZIVeGE6jIEafd3iPfGhWKdqNTlTUx024SjvT4BwvfASC2pfyZyy4aNYtr+tDrUebBectngzPRt0rf90w5EocSQVwmzls6ESEaHlLnkjYosGXG2ERCUXON7/I32x7k7LlLrilsIRCsbCweZtg4w7y8J9p1jVKlwCoqjJuGbM61u2veQSwuavzwI7aRSSvc5HrxzNUJc4Tzxxj3Ee+f+9WgKh32IOrPz/ozUTwLaigJXslCcxBzz0QTSGQ10iBXs=
  file:
    - "mdast-util-assert.js"
    - "mdast-util-assert.min.js"
  on:
    tags: true
    node: '9.0'
