language: node_js
node_js:
  - lts/dubnium
  - node
after_script: bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: SV8VkDgdyeShY/EfOQG5eaKcrKG7pDPrFkKywJBh1LutD9X4+9xqQvI3t1UCGEoJDmKJGA6BnY1HFLtVlSgM3/cLXLMog5uAEzEkBsYDBV1q3Ovt7thtq9ol+fA154L614LT6M8nALgm4s8DGMZExMXIhKDRiZDttetFkr1bGtYwTSWkbleOTpCUUQr8H4eGOgsWYFHd4FUC5AKGYL551LS8o49JJxCF1r2rSUeVzgwTGpE+H1A7Vj9aKS5WVXuxzrPdLzaVK4YbJF7m74cXVoirUGpZI76Bla84wZ599lPBw5Xc/1A1jPeLFSDhmRwbR8fULyj2AlWOOatP8/sgvZ/BtePvtvKG/3UkbraHLqs92O4SHMRTNRLoM2MI00qnDLZ8mLGOhdiIoui/fiJcD8NuJgFghs/SnMxIJWPknNI2b3yM3mTamnG+y4VvcTtP9q6AtfelMcXDlhZtQLCZsQCPQG3oN/z6OPyz3inrfmapapz/in7Od/fJ7fyH7YlqpD8rCuYhE2GgaCRQIYEk4MX9hzgAR1G/usI8/F0644zJ/pUVU8gBxe1FVf2LbirLzBGGFeQOPySWNsRgVElnMF50Hyi+RlmcK8eUczRN6na+Lt8LI4VNwgXe/p/Ixgo5F0sZYVkd4gkV/riViJqWHUO/3Nh3hx/cZ77AuuuwtuY=
  file:
    - 'mdast-util-assert.js'
    - 'mdast-util-assert.min.js'
  on:
    tags: true
